import Head from 'next/head'

const Seo = ({ title }) => {
  return (
    <Head>
      <title>{title} | ZU:MONEY</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Seo
