import Head from 'next/head'
import {Image, Layout, Menu} from "antd";
import Nav from "../components/Nav";
import Link from "next/link";
import React from "react";



export default function Home() {
    const {Header} = Layout
  return (
    <Layout>
      <Head>
        <title>ZU:MONEY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header style={{ position: 'fixed', zIndex: 1, width: '100%'}}>
            <div className="logo" > zu:money </div>
            <Nav />
        </Header>
    </Layout>
  )
}
